# Generated by Django 4.2.4 on 2023-09-28 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_driverprofile_license_expiry_date_and_more'),
        ('areas', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_id', models.CharField(editable=False, max_length=250, unique=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=39, null=True)),
                ('amount_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('amount_status', models.CharField(choices=[('DRAFT', 'Draft'), ('NOT PAID', 'Not Paid'), ('PAID', 'Paid')], default='NOT PAID', max_length=150)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('trip_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=25)),
                ('include_saturday', models.BooleanField(default=False)),
                ('include_sunday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hcustomer', to='accounts.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hmdriver', to='accounts.driver')),
                ('pickup_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areas.area')),
            ],
            options={
                'verbose_name': 'Hire us',
                'verbose_name_plural': 'Hire us',
            },
        ),
        migrations.CreateModel(
            name='HireusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('billing_start_date', models.DateField()),
                ('billing_end_date', models.DateField()),
                ('trip_count', models.IntegerField()),
                ('trip_attended', models.IntegerField()),
                ('amount_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('amount_status', models.CharField(choices=[('DRAFT', 'Draft'), ('NOT PAID', 'Not Paid'), ('PAID', 'Paid')], default='DRAFT', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hire_us.hireus')),
            ],
        ),
        migrations.CreateModel(
            name='HireTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(default=django.utils.timezone.now)),
                ('trip_status', models.CharField(choices=[('DRAFT', 'Draft'), ('INPROCESS', 'Inprocess'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='DRAFT')),
                ('trip_start_time', models.TimeField(blank=True, null=True)),
                ('trip_end_time', models.TimeField(blank=True, null=True)),
                ('trip_hours', models.DurationField(default=datetime.timedelta(seconds=7200), null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hdriver', to='accounts.driver')),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_trips', to='hire_us.hireus')),
            ],
        ),
        migrations.CreateModel(
            name='HireTripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_us.hireusreport')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hire_us.hiretrips')),
            ],
        ),
        migrations.CreateModel(
            name='DriverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_hours', models.DurationField()),
                ('driver_trip_count', models.IntegerField()),
                ('driver_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.driver')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_us.hireusreport')),
            ],
        ),
    ]
