# Generated by Django 4.2.4 on 2023-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireus',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hireus',
            name='report_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
