# Generated by Django 4.2.4 on 2023-09-28 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireus',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='hiretrips',
            name='trip_hours',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
