# Generated by Django 4.2.4 on 2023-09-05 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0002_alter_hireus_end_time_alter_hireus_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretrips',
            name='trip_hours',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
