# Generated by Django 4.2.4 on 2023-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0002_remove_hireus_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretrips',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('INPROCESS', 'Inprocess'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='DRAFT', null=True),
        ),
    ]
