# Generated by Django 4.2.4 on 2023-09-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0004_alter_hireus_options_alter_hiretrips_trip_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretrips',
            name='hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_trips', to='hire_us.hireus'),
        ),
    ]
