# Generated by Django 4.2.4 on 2023-10-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0004_alter_hiretrips_options_alter_hiretrips_trip_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireus',
            name='amount_status',
        ),
    ]
