# Generated by Django 4.2.4 on 2023-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0005_alter_hiretrips_hire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretrips',
            name='trip_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INPROCESS', 'Inprocess'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='DRAFT'),
        ),
    ]
