# Generated by Django 4.2.4 on 2023-10-09 13:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0005_remove_hireus_amount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireus',
            name='driver_cut_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='driverreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_report', to='hire_us.hireusreport'),
        ),
        migrations.AlterField(
            model_name='hiretripreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_trip_report', to='hire_us.hireusreport'),
        ),
        migrations.CreateModel(
            name='HirePaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_driver_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('driver_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire_us.driverreport')),
                ('hire_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_report', to='hire_us.hireusreport')),
            ],
        ),
    ]
