# Generated by Django 4.2.4 on 2023-10-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0006_hireus_driver_cut_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirepaymentreport',
            name='driver_report',
        ),
    ]
