# Generated by Django 4.2.4 on 2023-09-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire_us', '0006_alter_hiretrips_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreport',
            name='trip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hire_us.hiretrips'),
            preserve_default=False,
        ),
    ]
