# Generated by Django 4.2.4 on 2024-05-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
