# Generated by Django 4.2.4 on 2024-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
