# Generated by Django 4.2.4 on 2024-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
