# Generated by Django 4.1.6 on 2023-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='area',
            field=models.ManyToManyField(to='areas.area'),
        ),
    ]
