# Generated by Django 4.1.6 on 2023-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_city_options'),
        ('accounts', '0002_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='area',
            field=models.ManyToManyField(blank=True, to='areas.area'),
        ),
    ]
