# Generated by Django 4.2.1 on 2023-08-28 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driverprofile_address_alter_driverprofile_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_expiry_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(default='TN65 XXXXXXXXXX', max_length=50),
            preserve_default=False,
        ),
    ]
