# Generated by Django 4.2.4 on 2023-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
