# Generated by Django 4.2.4 on 2023-09-19 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
