# Generated by Django 5.1.4 on 2024-12-26 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_is_avaliable_driverprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='customer/profile_pic'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='driver/profile_pic'),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
