# Generated by Django 4.2.4 on 2024-05-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carenginetype_cartype_car_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_name',
        ),
    ]
