# Generated by Django 5.0.6 on 2024-11-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_engine_model', to='cars.carenginetype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_type', to='cars.cartype'),
        ),
    ]
