# Generated by Django 5.0.6 on 2024-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_engine_model_alter_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gas_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
