# Generated by Django 5.0.6 on 2024-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_gas_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='maker',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
