# Generated by Django 4.1.6 on 2023-02-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverwallettransaction',
            old_name='transation_type',
            new_name='transaction_type',
        ),
    ]
