# Generated by Django 4.1.6 on 2023-03-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0002_alter_city_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(editable=False, max_length=250, unique=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=39, null=True)),
                ('trip_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=25)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField()),
                ('drop_location', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amount_status', models.CharField(choices=[('NOT PAID', 'Not Paid'), ('PAID', 'Paid')], default='NOT PAID', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='accounts.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='accounts.driver')),
                ('pickup_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areas.area')),
                ('trip_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trips.triptype')),
            ],
        ),
    ]
