# Generated by Django 4.2.4 on 2024-04-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('trips', '0002_alter_trip_amount_alter_trip_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.car'),
        ),
    ]
