# Generated by Django 4.2.1 on 2023-05-16 14:23

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_amount_alter_trip_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
