# Generated by Django 4.2.1 on 2023-07-14 05:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_amount_alter_trip_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pickup_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
