# Generated by Django 4.2.1 on 2023-07-20 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_pickup_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='drop_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
