# Generated by Django 4.1.6 on 2023-02-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(editable=False, max_length=250, unique=True),
        ),
    ]
