# Generated by Django 5.0.6 on 2024-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_pickup_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_EN_ROUTE', 'Driver on the way'), ('TRIP_STARTED', 'Trip Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=25),
        ),
    ]
